### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by Tim020** [Tim020/Tiny-Storage#15]
The server crashes on startup with the following log: 

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 8/18/15 9:00 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
        at com.timthebrick.tinystorage.common.init.TinyStorageInitaliser.doColourMap(TinyStorageInitaliser.java:93)
        at com.timthebrick.tinystorage.common.init.TinyStorageInitaliser.postInit(TinyStorageInitaliser.java:55)
        at com.timthebrick.tinystorage.TinyStorage.postInit(TinyStorage.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.IIconRegister
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 34 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Windows 8.1 (amd64) version 6.3
        Java Version: 1.7.0_71, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 411830184 bytes (392 MB) / 1353187328 bytes (1290 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xmx2G -XX:MaxPermSize=256M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 122 mods loaded, 122 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar)
        UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10-universal.jar)
        UCHIJ   Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10-universal.jar)
        UCHIJ   CazzarCoreLib{1.2.0-SNAPSHOT} [Cazzar Core Lib](CazzarCoreLib-1.2.0-SNAPSHOT-universal.jar)
        UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar)
        UCHIJ   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar)
        UCHIJ   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar)
        UCHIJ   TubesCore{${version}} [Tubes Core](minecraft.jar)
        UCHIJ   backpacks16840{3.0.4} [Backpacks!](zz-backpacks 1.7.10 - 3.0.4.jar)
        UCHIJ   OpenModsCore{0.8} [OpenModsCore](minecraft.jar)
        UCHIJ   <CoFH ASM>{000} [CoFH ASM](minecraft.jar)
        UCHIJ   debug{1.0} [debug](denseores-1.6.2.jar)
        UCHIJ   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar)
        UCHIJ   PhaseBlocks{4.1.0} [PhaseBlocks](1.7.10-PhaseBlocks-4.1.0.jar)
        UCHIJ   LookingGlass{0.2.0.00} [Looking Glass](lookingglass-1.7.10-0.2.0.00.jar)
        UCHIJ   securitycraft{v1.8.0.6-beta} [SecurityCraft]([1.7.10] SecurityCraft 1.8.0.6-beta.jar)
        UCHIJ   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-13.jar)
        UCHIJ   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
        UCHIJ   CoFHCore{1.7.10R3.0.4B1} [CoFH Core](CoFHCore-[1.7.10]3.0.4B1-308.jar)
        UCHIJ   Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar)
        UCHIJ   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar)
        UCHIJ   chisel{2.4.1.40} [Chisel 2](Chisel2-2.4.1.40.jar)
        UCHIJ   koresample{1.7.10-1.3.2} [Kore Sample](KoreSample-1.7.10-1.3.2.jar)
        UCHIJ   StorageDrawers{1.7.10-1.5.14} [Storage Drawers](StorageDrawers-1.7.10-1.5.14.jar)
        UCHIJ   dendrology{1.7.10-1.6.2} [Ancient Trees](AncientTrees-1.7.10-1.6.2.jar)
        UCHIJ   AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar)
        UCHIJ   ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar)
        UCHIJ   ATG{0.10.0} [Alternate Terrain Generation](ATG-1.7.10-0.12.0.jar)
        UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar)
        UCHIJ   betterrain{0.15} [Better Rain](betterrain-1.7.2-1.7.10_0.15.jar)
        UCHIJ   betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar)
        UCHIJ   BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft[v1.10.6][MC1.7.10].jar)
        UCHIJ   ExtrabiomesXL{3.16.2} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.2.jar)
        UCHIJ   BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition](BiblioWoods[ExtraBiomesXL][v1.4].jar)
        UCHIJ   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar)
        UCHIJ   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar)
        UCHIJ   BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar)
        UCHIJ   redgear_core{2.2.0} [Red Gear Core](RedGearCore-1.7.10-2.2.0.jar)
        UCHIJ   redgear_brewcraft{1.2.3} [Brewcraft](Brewcraft-1.7.10-1.2.3.jar)
        UCHIJ   CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar)
        UCHIJ   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar)
        UCHIJ   ctmlib{1.0.1.5} [CTMLib](Chisel2-2.4.1.40.jar)
        UCHIJ   D3Core{1.1.0.30} [D3Core](D3Core-1.7.10-1.1.0.30.jar)
        UCHIJ   menagerie{1.0} [menagerie](dark_menagerie-1.7.10-beta-3.1a.jar)
        UCHIJ   props{2.0.2} [Decocraft](Decocraft-2.0.2_1.7.10.jar)
        UCHIJ   dimstorage{1.3} [DimStorage](DimStorage-1.7.2-1.3.jar)
        UCHIJ   Eln{50} [Electrical Age](ElectricalAge_BETA-1.10_r50.jar)
        UCHIJ   endercompass{1.1} [Ender Compass](EnderCompass-1.7.10-1.1.jar)
        UCHIJ   endercore{1.7.10-0.0.1.16_alpha} [EnderCore](EnderCore-1.7.10-0.0.1.16_alpha.jar)
        UCHIJ   EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar)
        UCHIJ   EnderZoo{1.7.10-1.0.15.32} [Ender Zoo](EnderZoo-1.7.10-1.0.15.32.jar)
        UCHIJ   eng_toolbox{1.2.3.0} [Engineer's Toolbox](EngineersToolbox-1.2.3.0-BETA.jar)
        UCHIJ   exoticbirds{1.0} [Exotic Birds](Exotic Birds for 1.7.10 by Pavocado.jar)
        UCHIJ   factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.95%282%29.jar)
        UCHIJ   factorization.dimensionalSlice{0.8.95} [Factorization Dimensional Slices](Factorization-1.7.10-0.8.95%282%29.jar)
        UCHIJ   factorization{0.8.95} [Factorization](Factorization-1.7.10-0.8.95%282%29.jar)
        UCHIJ   factorization.misc{0.8.95} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.95%282%29.jar)
        UCHIJ   farseek{1.0.8} [Farseek](Farseek-1.0.8.jar)
        UCHIJ   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar)
        UCHIJ   fastleafdecay{1.1} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.1.jar)
        UCHIJ   Steamcraft{0.28.10} [Flaxbeard's Steam Power](Flaxbeard'sSteamPower-1.7.10-0.28.10.jar)
        UCHIJ   fluxedtrinkets{0.54} [Fluxed Trinkets](Fluxed Trinkets-1.7.10-1.0.54.jar)
        UCHIJ   FoodPlus{3.2rS} [§bFood Plus](FoodPlus-1.7.2-3.2rS.jar)
        UCHIJ   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
        UCHIJ   fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar)
        UCHIJ   funkylocomotion{1.0} [Funky Locomotion](funky-locomotion-1.7.10-beta-7.jar)
        UCHIJ   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.357.jar)
        UCHIJ   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.357.jar)
        UCHIJ   GardenCore{1.7.10-1.6.3} [Garden Core](GardenStuff-1.7.10-1.6.3.jar)
        UCHIJ   GardenContainers{1.7.10-1.6.3} [Garden Containers](GardenStuff-1.7.10-1.6.3.jar)
        UCHIJ   GardenStuff{1.7.10-1.6.3} [Garden Stuff](GardenStuff-1.7.10-1.6.3.jar)
        UCHIJ   GardenTrees{1.7.10-1.6.3} [Garden Trees](GardenStuff-1.7.10-1.6.3.jar)
        UCHIJ   HardcoreDarkness{1.6} [Hardcore Darkness](HardcoreDarkness-MC1.7.10-1.6.jar)
        UCHIJ   HardcoreEnderExpansion{1.8.3} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar)
        UCHIJ   headcrumbs{1.6.0} [Headcrumbs](Headcrumbs-1.6.0.jar)
        UCHIJ   hungryanimals{1.7.10-10.13.2.1291-1.0.4.2} [Hungry Animals](hungryanimals-1.7.10-2.0.alpha02.jar)
        UCHIJ   ImmersiveEngineering{0.5.2} [Immersive Engineering](ImmersiveEngineering-0.5.2.jar)
        UCHIJ   immersiveintegration{0.4.2} [Immersive Integration](immersiveintegration-0.4.2.jar)
        UCHIJ   JukeboxReloaded{1.7.10} [Jukebox Reloaded](Jukebox-Reloaded-1.7.10-3.0.0-universal.jar)
        UCHIJ   LEDLighting{1.0.0} [LED Lighting](LEDLighting-1.0.0.jar)
        UCHIJ   LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar)
        UCHIJ   malisiscore{1.7.10-0.12.7} [MalisisCore](malisiscore-1.7.10-0.12.7.jar)
        UCHIJ   malisisdoors{1.7.10-1.9.4} [Malisis' Doors](malisisdoors-1.7.10-1.9.4.jar)
        UCHIJ   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.6.jar)
        UCHIJ   ModularArmour{1.0.0} [Modular Armour](ModularArmour-1.7.10-1.0.18-41.jar)
        UCHIJ   MorePlanet{1.2.9} [More Planets](More-Planets-1.7.10-1.2.9.jar)
        UCHIJ   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar)
        UCHIJ   MultiPageChest{1.3.4} [Multi Page Chest](MultiPageChest-1.3.4-MC1.7.10.jar)
        UCHIJ   NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar)
        UCHIJ   OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar)
        UCHIJ   OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar)
        UCHIJ   openmodularturrets{2.1.3-163} [Open Modular Turrets](OpenModularTurrets-1.7.10-2.1.3-163.jar)
        UCHIJ   PlaceableTools{1.2.0.33} [PlaceableTools](PlaceableTools-1.7.10-1.2.0.33.jar)
        UCHIJ   PneumaticCraft{1.10.6-119} [PneumaticCraft](PneumaticCraft-1.7.10-1.10.6-119-universal.jar)
        UCHIJ   progressiveautomation{1.6.27} [Progressive Automation](ProgressiveAutomation-1.7.10-1.6.27.jar)
        UCHIJ   realisticpain{2.0} [Realistic Pain](Realistic Pain-2.0-1.7.10.jar)
        UCHIJ   Records{0.1.0} [Additional Records](Records-0.1.0.zip)
        UCHIJ   RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar)
        UCHIJ   Redstonic{1.4.8} [Redstonic](Redstonic-v1.4.8.jar)
        UCHIJ   RIO{2.3} [RemoteIO](RemoteIO-1.7.10-2.3.B0-universal.jar)
        UCHIJ   roadblock{1.7.10-2.1.8-} [Roadblocks](Roadblocks-1.7.10-2.1.8.jar)
        UCHIJ   Roguelike{1.3.6.3} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.3.jar)
        UCHIJ   runicdungeons{1.1.5c} [Runic Dungeons](runicdungeons-1.1.5c.jar)
        UCHIJ   Schematica{1.7.6.127} [Schematica](Schematica-1.7.10-1.7.6.127-universal.jar)
        UCHIJ   simplyjetpacks{1.5.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.5.1.jar)
        UCHIJ   simply_sit{1.7.10-1.1.0} [Simply Sit](SimplySit-1.7.10-1.1.0.jar)
        UCHIJ   SpecialMobs{3.1.1} [Special Mobs](SpecialMobs-1.7.10-3.1.1.jar)
        UCHIJ   streams{0.1.4} [Streams](Streams-0.1.4.jar)
        UCHIJ   supercraftingframe{1.7.10.3} [Super Crafting Frame](supercraftingframe-1.7.10.3.jar)
        UCHIJ   erebus{0.2a} [Erebus](TheErebus-0.2b.jar)
        UCHIJ   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar)
        UCHIJ   thirstmod{1.8.14} [Thirst Mod](thirstmod-1.8.14.jar)
        UCHIE   TinyStorage{1.18.0_130-Dev} [Tiny Storage](TinyStorage-1.7.10_1.18.0_130-Dev.jar)
        UCHIJ   TooMuchTime{2.4.0} [TooMuchTime](TooMuchTime-1.7.10-2.4.0.B3-universal.jar)
        UCHIJ   TorchTools{1.2.0.26} [TorchTools](TorchTools-1.7.10-1.2.0.26.jar)
        UCHIJ   Tubes{2.0.5} [Tubes](Tubes-1.7.10-2.0.5.jar)
        UCHIJ   UndergroundBiomes{0.6h} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.6h13.jar)
        UCHIJ   ubcores{1.7.10-0.2.6.1} [UBC Ore Registrar](UBCOres-1.7.10-0.2.6.1.jar)
        UCHIJ   reaper_waterpipe{1.11} [Water Pipe mod](Waterpipe1.11[1.7.10].jar)
        UCHIJ   denseores{1.0} [Dense Ores](denseores-1.6.2.jar)
        UCHIJ   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
        UCHIJ   HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar)
        OpenModsLib class transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
        Class transformer null safety: all safe
        CoFHCore: -[1.7.10]3.0.4B1-308
        ThermalFoundation: -[1.7.10]1.2.0-102
        ThermalExpansion: -[1.7.10]4.0.3B1-218
        NetherOres: -[1.7.10]2.3.0-12
        RedstoneArsenal: -[1.7.10]1.1.1-89
        ThermalDynamics: -[1.7.10]1.1.0-161
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

Appears to be caused by the colour mapping referencing classes outside of the server - this should only be done client side and not server side.

**Comment by Tim020** [comment]
@OrionDevelopment any ideas on this, it is your function after all :D

**Comment by marchermans** [comment]
Donn't use it on the server side you dummy......
