### ISSUE TITLE
Crash on Server Startup with 1.20.0_152-Dev

### ISSUE THREAD

**Issue by rckymtnrfc** [Tim020/Tiny-Storage#16]
Using Forge 1492, fyi.  http://pastebin.com/zKSce61j

**Comment by marchermans** [comment]
Hello,

This bug has been fixed, yet @Tim020 still needs to release a new version of the code....... We are fixing some minor things regarding Gui stuff and hope to have a release ready version very soon.

**Comment by Tim020** [comment]
@OrionDevelopment, @rckymtnrfc 
The version you are using should have the fixes in place; I'll take a closer look at this and get back to you... My apologies though!

**Comment by Tim020** [comment]
Huh, so it seems that the changes I applied only got applied to the master branch and not the dev branch (hence why you crashed using the dev version)! Fix to follow...

**Comment by marchermans** [comment]
@Tim020 .......... I have no words for this madness!!!!!!!!!! (BTW You in TS?)

**Comment by Tim020** [comment]
I have no words either :P No not tonight, family stuff. Will be tomorrow though :)

**Comment by marchermans** [comment]
Oke
