### ISSUE TITLE
Crash with 1.9.0 RC - java.lang.ClassNotFoundException: com.timthebrick.tinystorage.proxy.ServerProxy

### ISSUE THREAD

**Issue by rckymtnrfc** [Tim020/Tiny-Storage#3]
http://pastebin.com/BYW3Wt3j

**Comment by Tim020** [comment]
Fixed in commit 32e17e764dc7f6279014b86f23d921f79fed53e6
Will get a fix release out asap

**Comment by Tim020** [comment]
@rckymtnrfc Should be fixed in the latest version either on Mods.IO or over on the Curse page
Let me know if this fixes your issue

**Comment by rckymtnrfc** [comment]
That appears to have resolved the issue.  Server started up instead of crashing.  Thanks for the quick reply/fix.  Looking forward to checking out your mod, just discovered it.  o/

**Comment by Tim020** [comment]
Glad that's solved it, hope you enjoy the content :) o/
