### ISSUE TITLE
Server crash on left click

### ISSUE THREAD

**Issue by rckymtnrfc** [Tim020/Tiny-Storage#4]
Sorry, got another one for you.  When I left click any block with an empty hand, the server crashes with the following:

http://pastebin.com/kKBgZJdw

**Comment by Tim020** [comment]
I can see that being a nuisance :P 
Working on it :)

**Comment by Tim020** [comment]
@rckymtnrfc
Hopefully fixed in 3cd575db69667e9c87ec0cc11b8ae213b0c834fc
Patched file here: http://tiny.cc/wsa3wx
Let me know if this works, and if it does I shall fully roll it out :)

**Comment by rckymtnrfc** [comment]
The left click crash is gone!  Thanks!  I also placed a few chests in the world and was able to access them without any issue. Figured I'd just quick test a few. Much appreciated.

**Comment by Tim020** [comment]
Woot, thanks for that! Much appreciated \o/
